-- ═══════════════════════════════════════════════════════════════
-- 023_maintenance_stock_link.sql  (requested as "006_..." —
-- renumbered into this repo's real sequence, already at 022)
--
-- Closes the loop between maintenance and inventory: logging a part
-- against a maintenance event now posts a real 'issue' transaction to
-- the stock ledger, and removing/cancelling that record posts the
-- reversing entry.
--
-- ─── DELIBERATE DEVIATIONS FROM THE LITERAL REQUEST ────────────
--
-- 1. BEFORE INSERT, not AFTER INSERT.
--    The request says AFTER INSERT and "write the resulting id back
--    into NEW.stock_transaction_id" — but NEW is not writable in an
--    AFTER trigger, so that shape needs a second UPDATE of the row we
--    just wrote. BEFORE INSERT sets the column in the same write. The
--    FK is still satisfied because the stock_transactions row is
--    inserted first, inside the trigger.
--
-- 2. The void path does NOT call void_stock_transaction().
--    That RPC is admin-only (migration 011). maintenance_events'
--    UPDATE policy allows department_user, so a department_user
--    cancelling an event would hit "Only admins may void a stock
--    transaction" and the whole cancel would fail. This migration
--    factors the reversal logic into void_stock_txn_internal() with
--    NO role gate, and rewrites void_stock_transaction() as a thin
--    admin-gated wrapper over it — same signature, same errors, same
--    behaviour for existing callers. The internal one is used by the
--    maintenance triggers, where the void is a *consequence* of an
--    action the user is already authorised to perform, not an
--    arbitrary edit of the ledger.
--
-- 3. Extra guard not in the request: editing quantity/part_id on a
--    maintenance_parts_used row that has already posted stock is
--    blocked. Without this, an edit silently desynchronises the
--    ledger from the maintenance record. See section 5.
--
-- NOT DONE ON PURPOSE: restoring a cancelled/soft-deleted event does
-- NOT re-post the stock. The reversal already happened and history is
-- immutable; re-logging the parts is the explicit, auditable action.
-- ═══════════════════════════════════════════════════════════════

-- ─── 1. Link columns on the ledger ──────────────────────────────
ALTER TABLE public.stock_transactions
  ADD COLUMN IF NOT EXISTS asset_id uuid REFERENCES public.assets(id),
  ADD COLUMN IF NOT EXISTS maintenance_event_id uuid REFERENCES public.maintenance_events(id);

CREATE INDEX IF NOT EXISTS stock_transactions_asset_idx
  ON public.stock_transactions (asset_id) WHERE asset_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS stock_transactions_maint_event_idx
  ON public.stock_transactions (maintenance_event_id) WHERE maintenance_event_id IS NOT NULL;

COMMENT ON COLUMN public.stock_transactions.asset_id IS
  'Set when this movement was generated by maintenance on a specific asset. NULL for ordinary store movements.';
COMMENT ON COLUMN public.stock_transactions.maintenance_event_id IS
  'The maintenance event that consumed this part, when applicable.';

-- ─── 2. Immutability trigger: cover the two new columns ─────────
-- The existing trigger compares every column old-vs-new and allows
-- only a false→true is_void flip. The two columns added above are not
-- in that list, so as written a void-UPDATE could also silently
-- rewrite them. Re-created here with both included.
CREATE OR REPLACE FUNCTION public.stock_transactions_block_mutation()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    RAISE EXCEPTION 'stock_transactions rows are immutable (id=%) — delete is not permitted. Post a reversing transaction instead.', OLD.id;
  END IF;

  IF OLD.is_void = false AND NEW.is_void = true
     AND NEW.id                    = OLD.id
     AND NEW.part_id               = OLD.part_id
     AND NEW.txn_type              = OLD.txn_type
     AND NEW.quantity              = OLD.quantity
     AND NEW.location_from         IS NOT DISTINCT FROM OLD.location_from
     AND NEW.location_to           IS NOT DISTINCT FROM OLD.location_to
     AND NEW.reference_no          IS NOT DISTINCT FROM OLD.reference_no
     AND NEW.unit_cost             IS NOT DISTINCT FROM OLD.unit_cost
     AND NEW.currency              = OLD.currency
     AND NEW.notes                 IS NOT DISTINCT FROM OLD.notes
     AND NEW.occurred_at           = OLD.occurred_at
     AND NEW.created_at            = OLD.created_at
     AND NEW.created_by            IS NOT DISTINCT FROM OLD.created_by
     AND NEW.reverses_txn_id       IS NOT DISTINCT FROM OLD.reverses_txn_id
     AND NEW.asset_id              IS NOT DISTINCT FROM OLD.asset_id
     AND NEW.maintenance_event_id  IS NOT DISTINCT FROM OLD.maintenance_event_id
  THEN
    RETURN NEW;
  END IF;

  RAISE EXCEPTION 'stock_transactions rows are immutable except for voiding (id=%). Post a reversing transaction instead of editing history.', OLD.id;
END;
$$;

-- ─── 3. Reversal logic, factored out of void_stock_transaction ──
-- Identical behaviour to the reversal half of migration 011's RPC,
-- minus the admin gate. Returns NULL (rather than raising) when the
-- transaction is already void, so trigger callers are idempotent.
CREATE OR REPLACE FUNCTION public.void_stock_txn_internal(p_txn_id uuid, p_reason text DEFAULT NULL)
RETURNS public.stock_transactions
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  orig            public.stock_transactions;
  reversing_type  public.stock_txn_type;
  new_txn         public.stock_transactions;
BEGIN
  SELECT * INTO orig FROM public.stock_transactions WHERE id = p_txn_id FOR UPDATE;
  IF orig.id IS NULL THEN
    RAISE EXCEPTION 'Stock transaction % not found', p_txn_id;
  END IF;
  IF orig.is_void THEN
    RETURN NULL;
  END IF;

  reversing_type := CASE orig.txn_type
    WHEN 'opening_balance'  THEN 'adjustment_out'
    WHEN 'receipt'          THEN 'adjustment_out'
    WHEN 'return_to_store'  THEN 'adjustment_out'
    WHEN 'adjustment_in'    THEN 'adjustment_out'
    WHEN 'transfer_in'      THEN 'transfer_out'
    WHEN 'issue'            THEN 'return_to_store'
    WHEN 'adjustment_out'   THEN 'adjustment_in'
    WHEN 'transfer_out'     THEN 'transfer_in'
    WHEN 'scrap'            THEN 'adjustment_in'
  END::public.stock_txn_type;

  UPDATE public.stock_transactions SET is_void = true WHERE id = p_txn_id;

  INSERT INTO public.stock_transactions (
    part_id, txn_type, quantity, location_from, location_to,
    reference_no, unit_cost, currency, notes, occurred_at, created_by, reverses_txn_id,
    asset_id, maintenance_event_id
  ) VALUES (
    orig.part_id, reversing_type, orig.quantity,
    orig.location_to, orig.location_from,
    orig.reference_no, orig.unit_cost, orig.currency,
    COALESCE(p_reason, 'Reversal of transaction ' || orig.id::text),
    now(), auth.uid(), orig.id,
    orig.asset_id, orig.maintenance_event_id
  ) RETURNING * INTO new_txn;

  RETURN new_txn;
END;
$$;

REVOKE ALL ON FUNCTION public.void_stock_txn_internal(uuid, text) FROM PUBLIC;

COMMENT ON FUNCTION public.void_stock_txn_internal(uuid, text) IS
  'Reversal engine shared by void_stock_transaction() and the maintenance triggers. NOT role-gated and NOT granted to authenticated — callers are responsible for authorisation. Returns NULL if the transaction is already void.';

-- void_stock_transaction() keeps its exact previous signature,
-- admin gate, and error messages — it now delegates the reversal.
CREATE OR REPLACE FUNCTION public.void_stock_transaction(p_txn_id uuid, p_reason text DEFAULT NULL)
RETURNS public.stock_transactions
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  new_txn public.stock_transactions;
BEGIN
  IF public.current_user_role() <> 'admin' THEN
    RAISE EXCEPTION 'Only admins may void a stock transaction';
  END IF;

  new_txn := public.void_stock_txn_internal(p_txn_id, p_reason);
  IF new_txn.id IS NULL THEN
    RAISE EXCEPTION 'Stock transaction % is already void', p_txn_id;
  END IF;
  RETURN new_txn;
END;
$$;

REVOKE ALL ON FUNCTION public.void_stock_transaction(uuid, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.void_stock_transaction(uuid, text) TO authenticated;

-- ─── 4. Post the issue when a part is logged ────────────────────
CREATE OR REPLACE FUNCTION public.maintenance_parts_post_issue()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  ev       public.maintenance_events;
  a_tag    text;
  p_code   text;
  p_del    timestamptz;
  new_txn  uuid;
BEGIN
  -- Idempotent: already linked to a transaction, nothing to do.
  IF NEW.stock_transaction_id IS NOT NULL THEN
    RETURN NEW;
  END IF;

  SELECT * INTO ev FROM public.maintenance_events WHERE id = NEW.maintenance_event_id;
  IF ev.id IS NULL THEN
    RAISE EXCEPTION 'Maintenance event % not found — cannot post the stock issue', NEW.maintenance_event_id;
  END IF;

  -- A cancelled or already-deleted event never consumed anything, so
  -- there is nothing to issue. (Restoring it later does not re-post —
  -- see the header note.)
  IF ev.status = 'cancelled' OR ev.deleted_at IS NOT NULL THEN
    RETURN NEW;
  END IF;

  SELECT code, deleted_at INTO p_code, p_del FROM public.spare_parts WHERE id = NEW.part_id;
  IF p_code IS NULL THEN
    RAISE EXCEPTION 'Spare part % does not exist — cannot post a stock issue for this maintenance record', NEW.part_id;
  END IF;
  IF p_del IS NOT NULL THEN
    RAISE EXCEPTION 'Spare part % is in the Trash — restore it before logging it against maintenance', p_code;
  END IF;

  SELECT asset_tag INTO a_tag FROM public.assets WHERE id = ev.asset_id;

  INSERT INTO public.stock_transactions (
    part_id, txn_type, quantity, unit_cost, occurred_at,
    reference_no, notes, created_by, asset_id, maintenance_event_id
  ) VALUES (
    NEW.part_id, 'issue', NEW.quantity, NEW.unit_cost,
    ev.event_date::timestamptz,
    COALESCE(NULLIF(ev.work_order_no, ''), 'MNT-' || ev.id::text),
    format('Consumed by %s on %s — %s', COALESCE(a_tag, 'unknown asset'), ev.event_date, ev.title),
    NEW.created_by, ev.asset_id, ev.id
  ) RETURNING id INTO new_txn;

  -- The existing trg_stock_transactions_recalc has already updated
  -- spare_parts.qty_on_hand — deliberately not duplicated here.
  NEW.stock_transaction_id := new_txn;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_maintenance_parts_post_issue ON public.maintenance_parts_used;
CREATE TRIGGER trg_maintenance_parts_post_issue
  BEFORE INSERT ON public.maintenance_parts_used
  FOR EACH ROW EXECUTE FUNCTION public.maintenance_parts_post_issue();

-- ─── 5. Block edits that would desynchronise the ledger ─────────
-- quantity/part_id are what the posted transaction was built from.
-- Changing them after the fact would leave the ledger saying one
-- thing and the maintenance record another, with no audit trail.
CREATE OR REPLACE FUNCTION public.maintenance_parts_block_desync()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  IF OLD.stock_transaction_id IS NOT NULL
     AND (NEW.quantity <> OLD.quantity OR NEW.part_id <> OLD.part_id) THEN
    RAISE EXCEPTION 'This part line already posted stock movement %. Delete the line and add it again instead of editing the part or quantity.', OLD.stock_transaction_id;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_maintenance_parts_block_desync ON public.maintenance_parts_used;
CREATE TRIGGER trg_maintenance_parts_block_desync
  BEFORE UPDATE ON public.maintenance_parts_used
  FOR EACH ROW EXECUTE FUNCTION public.maintenance_parts_block_desync();

-- ─── 6. Reverse when the record goes away ───────────────────────
CREATE OR REPLACE FUNCTION public.maintenance_parts_void_issue()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF OLD.stock_transaction_id IS NOT NULL THEN
    PERFORM public.void_stock_txn_internal(OLD.stock_transaction_id, 'Maintenance record removed');
  END IF;
  RETURN OLD;
END;
$$;

DROP TRIGGER IF EXISTS trg_maintenance_parts_void_issue ON public.maintenance_parts_used;
CREATE TRIGGER trg_maintenance_parts_void_issue
  AFTER DELETE ON public.maintenance_parts_used
  FOR EACH ROW EXECUTE FUNCTION public.maintenance_parts_void_issue();

-- Soft-deleting or cancelling the parent event reverses every part
-- line it posted.
CREATE OR REPLACE FUNCTION public.maintenance_event_void_stock()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  r RECORD;
BEGIN
  IF (NEW.deleted_at IS NOT NULL AND OLD.deleted_at IS NULL)
     OR (NEW.status = 'cancelled' AND OLD.status IS DISTINCT FROM 'cancelled') THEN
    FOR r IN
      SELECT stock_transaction_id FROM public.maintenance_parts_used
      WHERE maintenance_event_id = NEW.id AND stock_transaction_id IS NOT NULL
    LOOP
      PERFORM public.void_stock_txn_internal(r.stock_transaction_id, 'Maintenance record removed');
    END LOOP;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_maintenance_event_void_stock ON public.maintenance_events;
CREATE TRIGGER trg_maintenance_event_void_stock
  AFTER UPDATE ON public.maintenance_events
  FOR EACH ROW EXECUTE FUNCTION public.maintenance_event_void_stock();

-- ─── 7. Atomic event + parts RPC ────────────────────────────────
-- The frontend cannot span two inserts in one transaction over
-- PostgREST, so a partial failure would otherwise leave an event with
-- some of its parts (and some of its stock movements) posted. A
-- function body is a single transaction: everything here commits or
-- rolls back together.
--
-- SECURITY INVOKER on purpose — RLS still applies, so the caller
-- needs the same insert rights they would need doing it by hand.
CREATE OR REPLACE FUNCTION public.log_maintenance_event(
  p_asset_id       uuid,
  p_event_type     text,
  p_event_date     date,
  p_title          text,
  p_description    text    DEFAULT NULL,
  p_running_hours  numeric DEFAULT NULL,
  p_downtime_hours numeric DEFAULT NULL,
  p_work_order_no  text    DEFAULT NULL,
  p_performed_by   text    DEFAULT NULL,
  p_status         text    DEFAULT 'completed',
  p_failure_mode   text    DEFAULT NULL,
  p_root_cause     text    DEFAULT NULL,
  p_parts          jsonb   DEFAULT '[]'::jsonb
)
RETURNS public.maintenance_events
LANGUAGE plpgsql SECURITY INVOKER SET search_path = public AS $$
DECLARE
  ev   public.maintenance_events;
  item jsonb;
BEGIN
  INSERT INTO public.maintenance_events (
    asset_id, event_type, event_date, title, description,
    running_hours_at_event, downtime_hours, work_order_no, performed_by,
    status, failure_mode, root_cause, created_by
  ) VALUES (
    p_asset_id, p_event_type, p_event_date, p_title, p_description,
    p_running_hours, p_downtime_hours, p_work_order_no, p_performed_by,
    COALESCE(p_status, 'completed'), p_failure_mode, p_root_cause, auth.uid()
  ) RETURNING * INTO ev;

  FOR item IN SELECT * FROM jsonb_array_elements(COALESCE(p_parts, '[]'::jsonb))
  LOOP
    INSERT INTO public.maintenance_parts_used (
      maintenance_event_id, part_id, quantity, unit_cost, notes, created_by
    ) VALUES (
      ev.id,
      (item->>'part_id')::uuid,
      (item->>'quantity')::numeric,
      NULLIF(item->>'unit_cost', '')::numeric,
      NULLIF(item->>'notes', ''),
      auth.uid()
    );
  END LOOP;

  RETURN ev;
END;
$$;

GRANT EXECUTE ON FUNCTION public.log_maintenance_event(uuid,text,date,text,text,numeric,numeric,text,text,text,text,text,jsonb) TO authenticated;

-- ─── 8. Expose the asset on the movements view ──────────────────
-- Dropped and recreated rather than CREATE OR REPLACE: the new
-- columns land mid-list, and replace cannot reorder a view's columns.
DROP VIEW IF EXISTS public.v_stock_transactions_detail;

CREATE VIEW public.v_stock_transactions_detail AS
SELECT
  st.id, st.part_id, st.txn_type, st.quantity, st.signed_qty,
  st.location_from, st.location_to, st.reference_no, st.unit_cost, st.currency,
  st.notes, st.occurred_at, st.created_at, st.created_by, st.is_void,
  st.reverses_txn_id, st.is_estimated,
  st.asset_id, st.maintenance_event_id,
  SUM(CASE WHEN st.is_void THEN 0 ELSE st.signed_qty END)
    OVER (PARTITION BY st.part_id ORDER BY st.occurred_at, st.created_at, st.id
          ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS balance_after,
  sp.code AS part_code, sp.short_desc AS part_short_desc,
  sp.cat, sp.mfr, sp.model, sp.unit AS part_unit,
  a.asset_tag, me.title AS maintenance_title,
  up.email AS user_email, up.full_name AS user_full_name
FROM public.stock_transactions st
JOIN public.spare_parts sp ON sp.id = st.part_id
LEFT JOIN public.assets a ON a.id = st.asset_id
LEFT JOIN public.maintenance_events me ON me.id = st.maintenance_event_id
LEFT JOIN public.user_profiles up ON up.id = st.created_by;

COMMENT ON VIEW public.v_stock_transactions_detail IS
  'Read-only, denormalized stock_transactions for the Stock Movements page, now including the asset/maintenance event that generated the movement. balance_after is a running per-part sum of signed_qty (voided rows contribute 0). SECURITY INVOKER — see migration 014 for the user_profiles RLS caveat on user_email/user_full_name.';

GRANT SELECT ON public.v_stock_transactions_detail TO authenticated;

-- ═══════════════════════════════════════════════════════════════
-- OPTIONAL BACKFILL — READ BEFORE RUNNING
--
-- For maintenance_parts_used rows logged BEFORE this migration, which
-- have stock_transaction_id IS NULL and therefore never moved stock.
--
-- STEP 1 — dry run. See exactly what would be posted, and nothing
-- else. Run this on its own first:
--
--   SELECT mpu.id AS parts_used_id, sp.code AS part_code,
--          sp.qty_on_hand AS qty_now, mpu.quantity AS would_issue,
--          sp.qty_on_hand - mpu.quantity AS qty_after,
--          a.asset_tag, me.event_date, me.title, me.status
--   FROM public.maintenance_parts_used mpu
--   JOIN public.maintenance_events me ON me.id = mpu.maintenance_event_id
--   JOIN public.spare_parts sp ON sp.id = mpu.part_id
--   LEFT JOIN public.assets a ON a.id = me.asset_id
--   WHERE mpu.stock_transaction_id IS NULL
--     AND me.deleted_at IS NULL AND me.status <> 'cancelled'
--     AND sp.deleted_at IS NULL
--   ORDER BY me.event_date;
--
-- Check the row count and that qty_after is not unexpectedly
-- negative. Rows excluded by the WHERE clause (cancelled/deleted
-- events, trashed parts) are skipped on purpose — list them with the
-- same query minus those three conditions if you want to see them.
--
-- STEP 2 — post them. The UPDATE fires nothing on its own; it is the
-- INSERT inside the loop that posts, via the same trigger path as a
-- live entry, so the results are identical to having logged them
-- normally. Safe to re-run: rows already linked are skipped.
--
--   DO $backfill$
--   DECLARE r RECORD; v_txn uuid; v_count int := 0;
--   BEGIN
--     FOR r IN
--       SELECT mpu.id, mpu.part_id, mpu.quantity, mpu.unit_cost, mpu.created_by,
--              me.id AS event_id, me.event_date, me.title, me.work_order_no, me.asset_id,
--              a.asset_tag
--       FROM public.maintenance_parts_used mpu
--       JOIN public.maintenance_events me ON me.id = mpu.maintenance_event_id
--       JOIN public.spare_parts sp ON sp.id = mpu.part_id
--       LEFT JOIN public.assets a ON a.id = me.asset_id
--       WHERE mpu.stock_transaction_id IS NULL
--         AND me.deleted_at IS NULL AND me.status <> 'cancelled'
--         AND sp.deleted_at IS NULL
--     LOOP
--       INSERT INTO public.stock_transactions (
--         part_id, txn_type, quantity, unit_cost, occurred_at,
--         reference_no, notes, created_by, asset_id, maintenance_event_id
--       ) VALUES (
--         r.part_id, 'issue', r.quantity, r.unit_cost, r.event_date::timestamptz,
--         COALESCE(NULLIF(r.work_order_no,''), 'MNT-' || r.event_id::text),
--         format('Backfilled: consumed by %s on %s — %s',
--                COALESCE(r.asset_tag,'unknown asset'), r.event_date, r.title),
--         r.created_by, r.asset_id, r.event_id
--       ) RETURNING id INTO v_txn;
--
--       UPDATE public.maintenance_parts_used SET stock_transaction_id = v_txn WHERE id = r.id;
--       v_count := v_count + 1;
--     END LOOP;
--     RAISE NOTICE 'Backfilled % stock issue(s)', v_count;
--   END
--   $backfill$;
--
-- To undo a backfill, void the generated transactions (they are the
-- ones whose notes start with 'Backfilled:') — do not delete them.
-- ═══════════════════════════════════════════════════════════════

-- ═══════════════════════════════════════════════════════════════
-- ROLLBACK (commented out)
-- ═══════════════════════════════════════════════════════════════
-- DROP TRIGGER IF EXISTS trg_maintenance_event_void_stock ON public.maintenance_events;
-- DROP TRIGGER IF EXISTS trg_maintenance_parts_void_issue ON public.maintenance_parts_used;
-- DROP TRIGGER IF EXISTS trg_maintenance_parts_block_desync ON public.maintenance_parts_used;
-- DROP TRIGGER IF EXISTS trg_maintenance_parts_post_issue ON public.maintenance_parts_used;
-- DROP FUNCTION IF EXISTS public.maintenance_event_void_stock();
-- DROP FUNCTION IF EXISTS public.maintenance_parts_void_issue();
-- DROP FUNCTION IF EXISTS public.maintenance_parts_block_desync();
-- DROP FUNCTION IF EXISTS public.maintenance_parts_post_issue();
-- DROP FUNCTION IF EXISTS public.log_maintenance_event(uuid,text,date,text,text,numeric,numeric,text,text,text,text,text,jsonb);
-- -- Restore migration 011's standalone void_stock_transaction() body, then:
-- DROP FUNCTION IF EXISTS public.void_stock_txn_internal(uuid, text);
-- -- Restore migration 014's v_stock_transactions_detail definition, then:
-- -- DROP VIEW IF EXISTS public.v_stock_transactions_detail;
-- DROP INDEX IF EXISTS public.stock_transactions_maint_event_idx;
-- DROP INDEX IF EXISTS public.stock_transactions_asset_idx;
-- ALTER TABLE public.stock_transactions DROP COLUMN IF EXISTS maintenance_event_id;
-- ALTER TABLE public.stock_transactions DROP COLUMN IF EXISTS asset_id;
-- -- Also restore migration 011's stock_transactions_block_mutation() body.
